server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.datasource.url}
    username: ${mysql.datasource.username}
    password: ${mysql.datasource.password}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: mysql